/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    EditorCanvas: typeof import('./src/components/EditorCanvas.vue')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LayersPanel: typeof import('./src/components/LayersPanel.vue')['default']
    PropertiesPanel: typeof import('./src/components/PropertiesPanel.vue')['default']
    ScrubInput: typeof import('./src/components/ScrubInput.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
